### ISSUE TITLE
Subscription request and cancel must enqueue synchronously

### ISSUE THREAD

**Issue by zainab-ali** [zainab-ali/fs2-reactive-streams#29]
This surfaced in #28 .

According to [the Spec](https://github.com/reactive-streams/reactive-streams-jvm#3-subscription-code), calls to `request` after `cancel` must be noops.

However, the code for the two calls executes asynchronously.  It's entirely possible for the calls to occur out of order, and thus for the subscriber to receive unwanted messages:
```scala
//cancel
F.runAsync(requests.enqueue1(Cancelled))(_ => IO.unit).unsafeRunSync
//request
F.runAsync(requests.enqueue1(request))(_ => IO.unit).unsafeRunSync
```
The `unsafeRunSync` (I think) doesn't cause the end `IO` to be run synchronously.

**Comment by aeons** [comment]
Yeah, I've tried to wrap my head around the `runAsync -> unsafeRunSync` several times, and it does (as I understand it) cause the outer `IO`to be run synchronously, but the inner `IO`, that actually does stuff is still run async. And I'm not sure there's an obvious way to do what we want here.

**Comment by rossabaker** [comment]
I fixed it like this: https://github.com/rossabaker/fs2-reactive-streams/commit/c1ec2290241385dd8b5641709309d7c18ced98dc. Request and cancel have to decrement the semaphore to enqueue and increment it to release the lock for the next.  A semaphore felt like a heavy hammer, and I was happy to see my tests pass without it, but I just got (un)lucky.

**Comment by aeons** [comment]
Didn't notice that you removed the fix again :)

**Comment by zainab-ali** [comment]
Are you sure that fixes it?  For me, it reduces the occurrences a great deal, but doesn't completely eradicate the failure (I'm running in a for loop to test).

A semaphore will ensure that the calls can't happen concurrently, but it doesn't ensure that they will happen in the correct order.

**Comment by rossabaker** [comment]
Yes, you're right. My patch is not sufficient.

**Comment by zainab-ali** [comment]
It would work provided the semaphore was decremented synchronously.
For example, using a semaphore of `IO`:
```scala
  def cancel(): Unit = {
    semaphore.decrement.unsafeRunSync()
    F.runAsync(requests.enqueue1(Cancelled) >> 
    semaphore.increment.liftIO[F])(_ => IO.unit).unsafeRunSync
  }
```

**Comment by zainab-ali** [comment]
The async behaviour of a `semaphore.decrement` means that we need to use `IO` to force the code to run synchronously.
I don't like the solution above because it pollutes the code with a concrete `IO` type, which may not mix well with the end user's choice of effect.

It's possible to ensure a cancellation is synchronous by using a `Ref` as a cancellation flag and calling `setSyncPure`.
This is synchronous regardless of chosen `F`.

```scala
val flag: Ref[F, Boolean] = ???
def cancel(): Unit = {
  F.runAsync(flag.setSyncPure(true) >>
    requests.enqueue1(Cancelled)
  )(_ => IO.unit).unsafeRunSync()
}

def request(n: Long): Unit = {
  F.runAsync(flag.get >>= (cancelled =>
	if(cancelled) F.pure(())
	else requests.enqueue1(...)
    ))(_ => IO.unit).unsafeRunSync
}
```

Getting the flag is async, but an async get after a synchronous set will always return the correct value.

So for the following code:
```scala
subscription.cancel()
subscription.request(1)
subscription.request(2)
```

`cancel` always occurs before `request(1)`, but that `request(1)` and `request(2)` can get enqueued in any order.  This fixes the bug, and is still in accordance with the spec.

**Comment by zainab-ali** [comment]
This has been fixed in release `v0.2.3`.  Backporting will require a bit of effort, since the `fs2` constructs have changed a lot since `0.9`.

**Comment by rossabaker** [comment]
:+1:  I like this solution.  It works and the code is descriptive of the problem.

**Comment by zainab-ali** [comment]
I need to make a few changes in fs2 as discussed [here](https://github.com/functional-streams-for-scala/fs2/issues/923) before backporting.  It should be fairly straightforward.

**Comment by zainab-ali** [comment]
As discussed in #31 , the fs2 changes were unnecessary.  I've merged in the backport and will release v0.1.1 shortly.

**Comment by zainab-ali** [comment]
This has now been released in v0.1.1:tada:

**Comment by SystemFw** [comment]
I've just realised that I've spent a whole afternoon (during the subscription refactor) to understand a problem that was fully explained here 😞

**Comment by rossabaker** [comment]
Sorry about that. The test failure was familiar, but I didn't see the problem in your code. I should have pursued the history.

**Comment by SystemFw** [comment]
nah it's fine :)
I was a bit lazy in trying to understand the current code before rushing to rewrite it, so I deserved it :P

**Comment by zainab-ali** [comment]
My mistake - I should’ve rembered this one and prompted you, it took me a while to figure out last time, but it slipped my mind 😞
